spring.application.name=smart-wind-power-admin
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_wind_power
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
